<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuitForLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>601a3203-f7f7-470a-bf5f-1a179fdb45dc</testSuiteGuid>
   <testCaseLink>
      <guid>60f7a7cd-13c4-41f5-8b21-43d92b069e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_SwagLabs/Test_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b94ae2cb-f0dd-4cf6-8888-3af445ee0bf4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b94ae2cb-f0dd-4cf6-8888-3af445ee0bf4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>7cc6b803-f190-4782-b7ac-9c5d86803bbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b94ae2cb-f0dd-4cf6-8888-3af445ee0bf4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>b520dd21-3be2-4408-b5a6-5a37d5c7e0de</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
