<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Name(Z to A)</name>
   <tag></tag>
   <elementGuidId>9d6852e4-f869-4c12-8788-1b816d535fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='za']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>bbf3d35d-7ba8-4b9d-8ab4-0e297ff15f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1697548742603</value>
      <webElementGuid>3d83e011-6ce9-4ac5-b7cb-4fd560402198</webElementGuid>
   </webElementProperties>
</WebElementEntity>
